### ISSUE TITLE
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called

### ISSUE THREAD

**Issue by metametadata** [clj-pdf/clj-pdf#245]
There's a new log in stdout after bumping JVM:

```
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::invokeCleaner has been called by com.lowagie.text.pdf.MappedRandomAccessFile (file:/Users/yuri/.m2/repository/com/github/librepdf/openpdf/1.3.43/openpdf-1.3.43.jar)
WARNING: Please consider reporting this to the maintainers of class com.lowagie.text.pdf.MappedRandomAccessFile
WARNING: sun.misc.Unsafe::invokeCleaner will be removed in a future release
```

AFAIU, this will break the library in the future JVM versions.

Java version:

```
openjdk version "24.0.1" 2025-04-15
OpenJDK Runtime Environment GraalVM CE 24.0.1+9.1 (build 24.0.1+9-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 24.0.1+9.1 (build 24.0.1+9-jvmci-b01, mixed mode, sharing)
```

Lib version: 2.6.9.

<hr/>

I suspect the `com.github.librepdf/openpdf` should be bumped to at least  [2.0.4](https://github.com/LibrePDF/OpenPDF/releases/tag/2.0.4) as the `invokeCleaner` call was deleted  in https://github.com/LibrePDF/OpenPDF/pull/1319. 

This in turn will make Java 17 a min required version, see changelog in https://github.com/LibrePDF/OpenPDF/releases/tag/2.0.0.

**Comment by yogthos** [comment]
Thanks for the heads up, I bumped up openpdf to the latest. It looks like there aren't any breaking changes. I've pushed out 2.7.1 with the change. Let me know if it looks good on your end.

**Comment by yogthos** [comment]
oh you're right, seems like there were breaking changes after all

**Comment by metametadata** [comment]
Thank you, I see no issues in my app now 👍 

But just in case, some lib tests still fail on my machine, not sure if it's expected:  [tests.txt](https://github.com/user-attachments/files/21130138/tests.txt).

**Comment by yogthos** [comment]
There's a long running problem with keeping the tests stable because the tests attempt to compare binary output in the PDF, and unfortunately it's very tricky to keep it consistent. Different fonts on a machine and so on can cause these to fail. I end up checking the generated sample PDFs for tests manually as a sanity check.

If everything is working visually on your end, I think we can close the issue. And if anything new comes up, I can definitely take a look.
